### PR TITLE
UI UPDATED

### PR DESCRIPTION
**Pull request by himanshu251001**

### CODE REVIEW

**Comment by himanshu251001** [comment]
https://himanshu251001.github.io/Number-Guesser/

**Comment by Aakarsh05** [comment]
hey! the background is good. there is a slight problem with responsiveness of the page  and check the font colour.

**Comment by Aakarsh05** [comment]
host the website and then give it to me.

**Comment by himanshu251001** [comment]
> hey! the background is good. there is a slight problem with responsiveness of the page and check the font colour.

Ok

**Comment by himanshu251001** [comment]
> host the website and then give it to me.

I have made it responsive and for font color i have made few adjustment.But if you still feel of having different font colour i have made a backup with black font,if you need that just tell.

**Pull request closed without merging**
